name: Run browser tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'src/config/*'
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths-ignore:
      - 'src/config/**'
  workflow_dispatch:
    inputs:
      test_results_retention_days:
        description: 'Test results retention (in days)'
        required: true
        default: '7'
      node_version:
        description: 'NodeJS version'
        required: true
        default: '22.x'

jobs:
  test-browser:
    name: Run browser tests
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:

          # Stable releases
          - channel: stable
            chrome: stable
            coverage: true

          # Beta releases
          - channel: beta
            chrome: beta

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: ${{ matrix.chrome }}

      - name: Configure Karma with path to Chrome executable
        run: |
          chrome --version
          { echo CHROME_BIN="$(which chrome)"; echo CHROME_TEST=1; } | tee -a "$GITHUB_ENV"

      - name: Node setup
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node_version || '22.x' }}
          cache: npm

      - name: Install NPM dependencies
        run: npm install

      - name: Run injection tests
        run: npm run test:inject -- --ci --json --outputFile=test-results-inject.json

      - name: Run browser tests on Chromium MV2 build
        run: xvfb-run --auto-servernum npm run test:chrome -- --json --outputFile=test-results-chrome.json

      - name: Run browser tests on Chromium MV3 build
        run: xvfb-run --auto-servernum npm run test:chrome-mv3 -- --json --outputFile=test-results-chrome-mv3.json

      - name: Upload test results
        uses: actions/upload-artifact@v7
        with:
          name: test-results-chrome-${{ matrix.chrome }}-coverage-${{ matrix.coverage }}
          path: test-results-*
          retention-days: ${{ inputs.test_results_retention_days }}